title: <p align="center"> Madhu Omer </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://github.com/madhuomer0912">GitHub</a>
  
  <br>   
  This is part of Exercise.
  <br>
  </p>



theme: jekyll-theme-minimal
